import { Geist, Geist_Mono } from "next/font/google";

import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Suspense>
        {children}
          </Suspense>
  );
}
